# Generated by Django 5.0.4 on 2025-01-12 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('banner_image', models.ImageField(upload_to='campaign_banners/')),
                ('campaign_type', models.CharField(choices=[('ticket', 'Ticket'), ('media_selling', 'Media Selling'), ('meet_greet', 'Meet & Greet')], max_length=20)),
                ('deadline', models.DateTimeField()),
                ('ticket_limit_per_fan', models.PositiveIntegerField()),
                ('details', models.TextField()),
                ('winner_slots', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('winners_selected', models.BooleanField(default=False)),
                ('is_public_announcement', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaSellingCampaign',
            fields=[
                ('campaign_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaign.campaign')),
                ('media_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_media', models.PositiveIntegerField()),
                ('media_file', models.FileField(blank=True, null=True, upload_to='campaign_media/')),
            ],
            bases=('campaign.campaign',),
        ),
        migrations.CreateModel(
            name='MeetAndGreetCampaign',
            fields=[
                ('campaign_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaign.campaign')),
                ('ticket_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tickets', models.PositiveIntegerField()),
            ],
            bases=('campaign.campaign',),
        ),
        migrations.CreateModel(
            name='TicketCampaign',
            fields=[
                ('campaign_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaign.campaign')),
                ('ticket_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tickets', models.PositiveIntegerField()),
            ],
            bases=('campaign.campaign',),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets_purchased', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='campaign.ticketcampaign')),
            ],
        ),
    ]
