# Generated by Django 5.0.4 on 2025-01-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='auto_close_on_goal_met',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
