# Generated by Django 5.0.4 on 2025-01-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_campaign_auto_close_on_goal_met_campaign_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='exclude_previous_winners',
            field=models.BooleanField(default=False),
        ),
    ]
