# Generated by Django 5.0.4 on 2025-01-31 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_campaign_exclude_previous_winners'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='campaign.campaign')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
