# Generated by Django 5.0.4 on 2025-01-31 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_campaignwinner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='campaign.campaign'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='tickets_purchased',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
