# Generated by Django 5.0.4 on 2025-01-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_alter_participation_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='media_purchased',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
