# Generated by Django 5.0.4 on 2025-01-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_participation_media_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='ticket_limit_per_fan',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
