# Generated by Django 5.0.4 on 2025-02-10 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_alter_campaign_ticket_limit_per_fan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_campaigns', to=settings.AUTH_USER_MODEL),
        ),
    ]
