# Generated by Django 5.0.4 on 2025-03-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0010_purchasedmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
