# Generated by Django 5.0.4 on 2025-04-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0013_alter_participation_payment_method_escrowrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowrecord',
            name='tx_hash',
            field=models.CharField(blank=True, help_text='On-chain transaction hash', max_length=66, null=True),
        ),
    ]
