# Generated by Django 5.0.4 on 2025-04-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0014_alter_escrowrecord_tx_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowrecord',
            name='gas_cost_credits',
            field=models.BigIntegerField(default=0, help_text='Gas cost in credits'),
        ),
        migrations.AddField(
            model_name='escrowrecord',
            name='gas_cost_tt',
            field=models.BigIntegerField(default=0, help_text='Gas cost in TT'),
        ),
    ]
