# Generated by Django 5.0.4 on 2025-04-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0015_escrowrecord_gas_cost_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditspend',
            name='spend_type',
            field=models.CharField(choices=[('participation', 'Campaign Participation'), ('withdrawal', 'Withdrawal'), ('gas_fee', 'Gas Fee')], max_length=32),
        ),
    ]
