# Generated by Django 5.0.4 on 2025-06-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0017_creditspend_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='npn_campaign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='refund_on_deadline',
            field=models.BooleanField(default=False),
        ),
    ]
