# Generated by Django 5.0.4 on 2025-06-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0018_campaign_npn_campaign_campaign_refund_on_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for on-chain registration', max_length=255, null=True),
        ),
    ]
