# Generated by Django 5.0.4 on 2025-06-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0019_campaign_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='task_id',
        ),
        migrations.AddField(
            model_name='escrowrecord',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for on-chain registration', max_length=255, null=True),
        ),
    ]
