# Generated by Django 5.0.4 on 2025-05-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
