# Generated by Django 5.0.4 on 2025-01-12 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_delete_fan_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 12, 9, 9, 51, 281506, tzinfo=datetime.timezone.utc)),
        ),
    ]
