# Generated by Django 5.0.4 on 2025-01-25 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 25, 10, 30, 9, 774543, tzinfo=datetime.timezone.utc)),
        ),
    ]
