# Generated by Django 5.0.4 on 2025-02-01 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 1, 0, 20, 47, 343441, tzinfo=datetime.timezone.utc)),
        ),
    ]
