# Generated by Django 5.0.4 on 2025-02-03 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 3, 22, 8, 26, 700064, tzinfo=datetime.timezone.utc)),
        ),
    ]
