# Generated by Django 5.0.4 on 2025-02-08 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 8, 21, 13, 26, 413833, tzinfo=datetime.timezone.utc)),
        ),
    ]
