# Generated by Django 5.0.4 on 2025-02-10 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_profile_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 10, 15, 45, 30, 435901, tzinfo=datetime.timezone.utc)),
        ),
    ]
