# Generated by Django 5.0.4 on 2025-02-11 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 1, 58, 57, 220284, tzinfo=datetime.timezone.utc)),
        ),
    ]
