# Generated by Django 5.0.4 on 2025-02-11 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 12, 25, 25, 387125, tzinfo=datetime.timezone.utc)),
        ),
    ]
