# Generated by Django 5.0.4 on 2025-02-12 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 12, 0, 43, 28, 929531, tzinfo=datetime.timezone.utc)),
        ),
    ]
