# Generated by Django 5.0.4 on 2025-02-12 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='phone_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 12, 23, 47, 49, 117675, tzinfo=datetime.timezone.utc)),
        ),
    ]
