# Generated by Django 5.0.4 on 2025-02-15 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_verificationcode_email_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 14, 53, 18, 653180, tzinfo=datetime.timezone.utc)),
        ),
    ]
