# Generated by Django 5.0.4 on 2025-02-15 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 14, 56, 55, 946812, tzinfo=datetime.timezone.utc)),
        ),
    ]
