# Generated by Django 5.0.4 on 2025-02-25 12:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 13, 5, 15, 67285, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='ReportGenericIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_category', models.CharField(help_text='Category of the issue (e.g., Bug, Feature Request, Other)', max_length=100)),
                ('details', models.TextField(help_text='Detailed description of the issue')),
                ('attachment', models.FileField(blank=True, help_text='Optional attachment (image or file) related to the issue', null=True, upload_to='reported_issues/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who reported the issue', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
