# Generated by Django 5.0.4 on 2025-03-04 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_verificationcode_expires_at_socialmedialink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 4, 11, 47, 1, 872060, tzinfo=datetime.timezone.utc)),
        ),
    ]
