# Generated by Django 5.0.4 on 2025-03-11 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 22, 12, 12, 519226, tzinfo=datetime.timezone.utc)),
        ),
    ]
