# Generated by Django 5.0.4 on 2025-03-14 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 14, 3, 31, 57, 213682, tzinfo=datetime.timezone.utc)),
        ),
    ]
