# Generated by Django 5.0.4 on 2025-03-21 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 6, 38, 53, 790620, tzinfo=datetime.timezone.utc)),
        ),
    ]
