# Generated by Django 5.0.4 on 2025-04-19 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(blank=True, default=None, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 19, 0, 20, 6, 355679, tzinfo=datetime.timezone.utc)),
        ),
    ]
