# Generated by Django 5.0.4 on 2025-04-19 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_customuser_user_id_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 19, 0, 22, 0, 658225, tzinfo=datetime.timezone.utc)),
        ),
    ]
