# Generated by Django 5.0.4 on 2025-04-19 02:04

from django.db import migrations
import uuid

def backfill_user_ids(apps, schema_editor):
    CustomUser = apps.get_model('api', 'CustomUser')
    for user in CustomUser.objects.all():
        # if for some reason it’s already set, skip
        if not user.user_id:
            user.user_id = uuid.uuid4().hex
            # update only that one field
            user.save(update_fields=['user_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.RunPython(backfill_user_ids, reverse_code=migrations.RunPython.noop),
    ]
