# Generated by Django 5.0.4 on 2025-04-19 02:08

import api.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20250419_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default=api.models.generate_user_id, editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 19, 2, 18, 55, 146771, tzinfo=datetime.timezone.utc)),
        ),
    ]
