# Generated by Django 5.0.4 on 2025-04-21 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_customuser_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 21, 10, 29, 23, 716545, tzinfo=datetime.timezone.utc)),
        ),
    ]
