# Generated by Django 5.0.4 on 2025-04-29 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 29, 3, 4, 0, 931151, tzinfo=datetime.timezone.utc)),
        ),
    ]
