# Generated by Django 5.0.4 on 2025-05-10 20:55

import api.utils
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_customuser_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default=api.utils.generate_user_id_int, editable=False, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 10, 21, 5, 2, 158343, tzinfo=datetime.timezone.utc)),
        ),
    ]
