# Generated by Django 5.0.4 on 2025-05-16 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_customuser_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='withdraw_email_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='withdraw_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='withdraw_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='withdraw_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='withdraw_phone_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='withdraw_phone_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='withdraw_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 22, 1, 4, 74550, tzinfo=datetime.timezone.utc)),
        ),
    ]
