# Generated by Django 5.0.4 on 2025-06-12 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_verificationcode_withdraw_email_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 12, 11, 38, 16, 300579, tzinfo=datetime.timezone.utc)),
        ),
    ]
