# Generated by Django 5.0.4 on 2025-06-17 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_alter_verificationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 17, 11, 48, 18, 767514, tzinfo=datetime.timezone.utc)),
        ),
    ]
